### ISSUE TITLE
How to handle url("data: 

### ISSUE THREAD

**Issue by GabrielDelepine** [niksy/stylelint-no-unresolved-module#4]
Hi,

I have this kind of `url("data:........")` in my code base.
Shouldn't they be ignored by the plugin? I wonder what's your view on this.

![Screenshot 2023-09-07 at 12 49 22](https://github.com/niksy/stylelint-no-unresolved-module/assets/1979087/10603432-8eb2-4f2b-8caa-16544e896202)

![Screenshot 2023-09-07 at 12 49 31](https://github.com/niksy/stylelint-no-unresolved-module/assets/1979087/158817c1-4034-4768-84c4-71606a12f3fb)

My quick solution for now: make image files instead of inlining them within the CSS

Regards,

**Comment by GabrielDelepine** [comment]
Finally, it's easier to use the following comment

`/* stylelint-disable-next-line plugin/no-unresolved-module */`

![Screenshot 2023-09-07 at 16 15 11](https://github.com/niksy/stylelint-no-unresolved-module/assets/1979087/6c75c696-ce79-42a7-8058-fdc0afb0b2ae)

**Comment by niksy** [comment]
Yeah, `data` URLs should be ignored. Two approaches you mentioned are easiest way to ignore it, but I’ve pushed new patch release so you don’t need to do that. Thanks for the report!
